---

##
## win_jenkins_sshslave_args:
##
##   jenkins_base: ## optional, passthrough jenkins base role args
##
##   ssh_server: ## optional, passthrough ssh server args
##
##   remote_fs: ## mandatory
##     disabled: ## optional, set it to true to disable remote fs handling completly
##     real_path: ## absolute valid path on remote machine where the remote-fs-dir will be put
##     link_path: ## absolute valid path on remote machine where a symlink to realpath is put, optional, defaults to c:\<real_path>
##
##     ## autolinking means the internal default method of creating a symlink on c: 
##     ## drive for any realpath which lies on another drive, reason is that stuff 
##     ## can get complicated very fast when jenkins remote-fs is not on c: drive, 
##     ## first of all one need additional drive switching commands in jenkins node 
##     ## setting (not that bad), another much more complex issue is that current 
##     ## win docker and jenkins docker plugin volume mapping only work properly if 
##     ## volumes are on c: drive, which means jenkins workspaces must be on c: 
##     ## which means remote-fs must be on c:
##     no_autolinking: ## optionally set this to disable autolinking method completly, defaults to False
##

  - smabot.windows.normalize_jenkins_slave_ssh_args:
    register: _tmp_normres

  - set_fact:
      jenkins_sshslave_args_normed: "{{ _tmp_normres.normalized }}"


    ## handle ssh server
  - import_role:
      name: smabot.windows.builtin_ssh_server
    vars:
      winbuiltin_sshserver_args: "{{ jenkins_sshslave_args_normed.ssh_server }}"


    ## handle java
  - import_role:
      name: smabot.windows.jenkins_slave_base
    vars:
      jenkins_slave_base_args: "{{ jenkins_sshslave_args_normed.jenkins_base }}"


    ## handle remote-fs
  - block:

      - name: assure that jenkins remote-fs exists  ==>> {{ jenkins_sshslave_args_normed.remote_fs.real_path }}
        ansible.windows.win_file:
          path: "{{ jenkins_sshslave_args_normed.remote_fs.real_path }}"
          state: directory

      - block:

          - smabot.base.warn:
              msg: >-
                Neither remote-fs realpath
                '{{ jenkins_sshslave_args_normed.remote_fs.real_path }}' nor
                remote-fs linkpath
                '{{ jenkins_sshslave_args_normed.remote_fs.link_path }}' are
                on 'c:' drive. Be aware that this increases the probability
                of issues, especially when you also use docker in jenkins.

            when: jenkins_sshslave_args_normed.remote_fs._none_on_c

          - name: autolinking jenkins remote-fs '{{ jenkins_sshslave_args_normed.remote_fs.real_path }}' <==> '{{ jenkins_sshslave_args_normed.remote_fs.link_path }}'
            smabot.windows.fs_link:
              link_path: "{{ jenkins_sshslave_args_normed.remote_fs.link_path }}"
              target_path: "{{ jenkins_sshslave_args_normed.remote_fs.real_path }}"
              overwrite: true
              state: present
              ##force: true

        when: not jenkins_sshslave_args_normed.remote_fs.no_autolinking

    when: jenkins_sshslave_args_normed.remote_fs

