---

## TODO:
## ##jenkins_slave_args:
## ##  ## if set assumes that git-bash is installed and use as "distro" base for utilities like ssh-agent and such
## ##  use_gitbash: true  ## simply set to true to use default path, defaults to false
## ##  use_gitbash: C:\foo\bar\baz  ## alternatively one can specify a concret path where git bash can be found
## ##  agent: ## mandatory 
## ##    master_url: ## mandatory
## ##    node_name: ## mandatory
## ##    secret: ## mandatory
## ##    workdir: ## mandatory
## ##    agent_url: ## optional, defaults to: <master_url>/jnlpJars/agent.jar
## ##    node_url: ## optional, defaults to: <master_url>/computer/<node_name>/slave-agent.jnlp
## ##    default_params: true/false ## optional, can be used to disable all default agent params, true on default
## ##    params: ## optional, defaults to empty
## ##  service: ## optional, properly defaulted
## ##  disable_winssh: true ## optional, defaults to false
## ##  enable_default_java: true ## optional, defaults to false
## ##  default_java_extra_args: ## optional, defaults to empty
## ##    version: '8.232.9'
## 
##   - smabot.windows.normalize_jenkins_slave_args:
##     register: _tmp_normres
## 
##   - set_fact:
##       jenkins_slave_args_normed: "{{ _tmp_normres.normalized }}"
## 

  - import_role:
      name: smabot.windows.builtin_ssh_server

# TODO: pass through args
##    vars:
##      winbuiltin_sshserver_args:


    ## TODO: do java, unify with other jenkins slave role
    ##    ## default java deselected
    ##  - block:
    ##
    ##      - name: check if java is installed
    ##        smabot.windows.command_info:
    ##          command: java
    ##          type: Application
    ##        register: _res_find_java
    ##
    ##      - ansible.builtin.assert:
    ##          that: >-
    ##            ansible_env.JAVA_HOME is defined or
    ##            _res_find_java.command_info.get('java.exe', False) is truthy
    ##          fail_msg: >-
    ##            windows jenkins slave needs java installed on target machine, 
    ##            either make sure it is installed before calling this role or 
    ##            enable default java installation by setting 
    ##            jenkins_slave_args.enable_default_java to true
    ##
    ##    when: not jenkins_slave_args_normed.enable_default_java
    ##
    ##
    ##    ## default java selected
    ##  - block:
    ##
    ##      - set_fact:
    ##          _tmp_java_inst_args: >-
    ##            {{ { 'name': 'adoptopenjdk8jre', 'state': 'present' } 
    ##             | combine(jenkins_slave_args_normed.default_java_extra_args) }}
    ##
    ##      - name: install default java runtime for jenkins
    ##        chocolatey.chocolatey.win_chocolatey: "{{ _tmp_java_inst_args }}"
    ##
    ##    when: jenkins_slave_args_normed.enable_default_java
    ##

    ## TODO: mklink jenkins root dir to c: when on different drive, because windows docker volume mapping only works with C: drive

