---

## winbuiltin_sshserver_args:
##   service: ## optional
##     state: ## optional, defaults to started
##     password: ## optional, defaults to empty string
##   firewall: ## optional
##     state: ## optional, defaults to present
##     enabled: ## optional, defaults to true
##     <other passthrough interface params> ## optional

  - smabot.windows.normalize_winbuiltin_sshserver_args:
    register: _tmp_normres

  - set_fact:
      winbuiltin_sshserver_args_normed: "{{ _tmp_normres.normalized }}"

##  - import_role:
##      name: smabot.windows.win_capability
##    vars:
##      win_capability_args:
##        task_name: make sure openssh server windows feature is enabled
##        cap_args: 
##          caps: .*openssh.*server.*
##          state: present

    ##
    ## note: normally should the install step above already create a 
    ##   proper firewall rule, we will query it here as base
    ##
  - name: query ssh server default rule
    smabot.windows.query_firewall_rules:
      search_query: "*ssh*"
      expect_max: 1
    register: _tmp_res_query

  - set_fact:
      _tmp_args_in: >-
        {{ ( _tmp_res_query.rule | default({}, True) ) 
         | combine(
             winbuiltin_sshserver_args_normed.firewall, recursive=True
         ) }}

    ## TODO: this was unexpectly yellow on the first time, but there should be no changes, so why??
  - name: configure firewall for ssh server traffic
    community.windows.win_firewall_rule: "{{ _tmp_args_in }}"


  - name: query ssh server winservice
    ansible.windows.win_service:
      name: sshd
    register: _tmp_res_query

  - set_fact:
      _tmp_args_in: >-
        {{ ( _tmp_res_query
             | smabot.base.subdict(keys_keep=[
              'name', 'display_name', 'description', 
              'dependencies', 'desktop_interact', 'path', 
              'start_mode', 'username'
             ]) 
           ) | combine(winbuiltin_sshserver_args_normed.service) }}

  - name: manage ssh server winservice
    ansible.windows.win_service: "{{ _tmp_args_in }}"

