---

## winservice_nssm_args:
##   nssm: ## optional, empty default
##   service: ## mandatory
##     name: ## mandatory
##     user: ## optional, defaults to LocalSystem
##     custom_pathvar: ## optional
##     create: ## mandatory
##       application:
##       arguments:
##       working_directory:
##       description:
##       display_name:
##     config: ## optional

  - smabot.windows.normalize_winservice_nssm_args:
    register: _tmp_normres

    ## note: for correctly resolving $PATH var during normalisation 
    ##   we must run this as the service user
    become: yes
    become_user: >-
      {{ winservice_nssm_args.service.user | default('System', True) }}

  - set_fact:
      winservice_nssm_args_normed: "{{ _tmp_normres.normalized }}"


  - name: ensure nssm is avaible
    win_chocolatey: "{{ winservice_nssm_args_normed.nssm }}"


  - name: >-
      create win service wrapper ==> {{ winservice_nssm_args_normed.service.create.name }}
    community.windows.win_nssm: "{{ winservice_nssm_args_normed.service.create }}"


  - name: >-
      configure new win service ==> {{ winservice_nssm_args_normed.service.create.name }}
    win_service: "{{ winservice_nssm_args_normed.service.config }}"

