---

    ##
    ## note: as to my understanding we must pass the password on stdin
    ##   (so per prompt) it is unfortunately possible that this call
    ##   might hang, so use ansible async/poll system to assure a
    ##   maximal timeout
    ##
    ## update: not totally sure yet if above is really true/necessary
    ##
  - name: (de-) join machine to active directory
    smabot.windows.join_winad_realm: >-
      {{ _tmp_smabot_windows_linux_adjoin_join_cfg }}

    ##
    ## note: depending on your network it is possible that this might
    ##   fail sporadically, so we add some repetetion here to make it
    ##   more robust
    ##
    register: _tmp_res_adjoin
    until: _tmp_res_adjoin is not failed
    retries: "{{ smabot_windows_linux_adjoin_args_normed.join.retries.num }}"
    delay: "{{ smabot_windows_linux_adjoin_args_normed.join.retries.delay }}"

    ##async: 60
    ##poll: 5

